name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - pycdfpp
  - matplotlib
  - bqplot
  - numpy
  - ipympl
  - ipydatagrid
  - pandas
  - requests
  - xarray
  - PyYAML
  - tqdm
  - astropy
  - scikit-learn
  - scipy
  - pip:
    - diskcache 
    - appdirs 
    - humanize
    - speasy>=1.7.1
    - pyistp
    - astroquery
